### ISSUE TITLE
Tries to fetch details where there are none (anymore)

### ISSUE THREAD

**Issue by sergioc** [freaktechnik/advanced-github-notifier#16]
Installed AGN on FF 50.1.0, authorized it in Github. It never shows there's notifications - no badge count, "no notifications" on menu if I click AGN icon.

**Comment by freaktechnik** [comment]
Have you tried the version from the beta release channel? https://addons.mozilla.org/en-US/firefox/addon/advanced-github-notifier/versions/beta

If it still happens, could you open the Browser Console (in the Dev Tools menu) and disable & re-enable the extension and look out for github related logging? It'd probably be helpful to also show XHRs (in the request filter category).

Thanks!

**Comment by sergioc** [comment]
I've just tried 1.1.0pre1, still no luck.

**Comment by sergioc** [comment]
Let me know if I can somehow help fix the issue.

**Comment by freaktechnik** [comment]
> If it still happens, could you open the Browser Console (in the Dev Tools menu) and disable & re-enable the extension and look out for github related logging? It'd probably be helpful to also show XHRs (in the request filter category).

**Comment by sergioc** [comment]
OK, disabling and re-enabling shows the following in the browser console:

```
404  background.js:166:21
	getNotifications/<     moz-extension://3dca750d-ddf8-ca4c-b9e9-b77c258d94ca/scripts/background.js:166:21
uncaught exception: 404
```

Is that enough? What kind of info are you looking for in the XHRs?

**Comment by freaktechnik** [comment]
Hm, so you're getting a 404 Error on https://api.github.com/notifications

**Comment by freaktechnik** [comment]
The only thing I can think of that could be differebt for you and would be visible in the logged request are the headers. In theory the code only adds the required OAuth headers and that's it. With invalid OAuth headers the response should be 400 or similar, not 404.

**Comment by sergioc** [comment]
What can I do to help?

**Comment by freaktechnik** [comment]
If you select XHR in the "Net" filter menu of the browser console, you should see almost all requests that are happening in the browser.  You should then also see the request to https://api.github.com/notifications that gets a 404 response. To make it easier to find it you can filter for "github" in the search field in the top right. Click on the arrow to the left of the request and copy the response and request headers. Please make sure you remove the Authorization token if it looks like a valid token in the request headers before posting them (looks like `Authorization token 123456789746abacdstt56421321bs? - actual token is made up here). All other headers should not contain sensitive information and the hashes etc. are mostly caching information.

**Comment by freaktechnik** [comment]
I just noticed that it might also be a call to get the details of a notification that fails, because the subject of it is no longer found. The call that 404s would look a lot different in that case and the extension should handle that more gracefully in that case.

**Comment by sergioc** [comment]
Here's a list of all calls (with full repo URLs redacted):

<img width="1282" alt="screenshot 2017-01-18 16 55 12" src="https://cloud.githubusercontent.com/assets/493451/22071306/02e670aa-dd9f-11e6-9764-2af6a71a0dd3.png">

There's one GET and one OPTIONS call to https://api.github.com/notifications - which do you need?

**Comment by freaktechnik** [comment]
Huh, so it seems to call api.github.com/repos/, I'll have to look into when that can happen. Thanks for the report!

**Comment by sergioc** [comment]
Let me complicate things a bit more: the extension works now without me having done anything...

**Comment by freaktechnik** [comment]
It seems the notification that had an invalid detail URL (the github API provides an API endpoint that holds more info on the object of the notification) either moved out of the first page the extension fetches (it only fetches the first page of notifications currently) or was marked read, or github fixed it.

Either way, the extension shouldn't stop working just because the details of a notification couldn't be found.

**Comment by freaktechnik** [comment]
This should be fixed for good in pre3 (https://addons.mozilla.org/en-US/firefox/addon/advanced-github-notifier/versions/beta)

**Comment by sergioc** [comment]
I'm using pre3 and the count badge still doesn't show reliably. Right now I have several notifications and the AGN doesn't even show a badge :-(

Browser console:

<img width="769" alt="screenshot 2017-01-23 15 07 22" src="https://cloud.githubusercontent.com/assets/493451/22207074/00323686-e17e-11e6-8aba-5aa6446a7d2f.png">

**Comment by freaktechnik** [comment]
hmm, it should ignore all those 404s and just show the notifications that

**Comment by sergioc** [comment]
OK, now all of a sudden it's working - I wonder if browser cache is playing tricks here.  I have full access rights to all the repos giving 404. I'm going to clean my browser's cache and report back tomorrow.

P.S. Is there a way to choose how many notifications show in the AGN's menu instead of limiting to only 2?

**Comment by freaktechnik** [comment]
It should show all notifications at all times.
