### ISSUE TITLE
No data retrieved after update?

### ISSUE THREAD

**Issue by tooomm** [freaktechnik/advanced-github-notifier#336]
**Describe the bug**
After auto updating to 1.9.5, no notifications show in the list.

**Firefox (please complete the following information):**

- OS: Windows 10
- Firefox Version: 100.0.2
- Extension version: 1.9.5

**Additional context**
I also restarted Firefox and tried deactivating and reactivating the extension.

**Comment by freaktechnik** [comment]
Fixed in v1.9.6.

**Comment by tooomm** [comment]
Unfortunately, 1.9.6 did not solve the issue. I also disabled/enabled and restarted FF again.

I think I had this issue before and ended up removing and reconnecting my account after a few days...

**Comment by freaktechnik** [comment]
You might have to re-add the GitHub account yeah, I think there's something not quite right with the token logic, see also #337

**Comment by tooomm** [comment]
>I think there's something not quite right with the token logic, see also https://github.com/freaktechnik/advanced-github-notifier/issues/337

Looks like it, yeah. Re-adding the GH account worked immediately!
